@startuml

actor Operator as Operator
participant "MES API" as MES_API
collections "Cache" as Cache
database "MES db" as MES_DB

Operator -> MES_API: Get orders
MES_API <-- Cache: Return orders or null
alt orders is null
    MES_API -> MES_DB: Get orders
    MES_API <-- MES_DB: Return orders
    MES_API -> Cache: Cache orders
end

Operator <-- MES_API: Return orders
@enduml